### PR TITLE
Mec172x hal 001

### PR DESCRIPTION
**Pull request by scottwcpg**
Added MEC172x HAL headers.  MCHP team generating headers generates complete headers for each chip instead of creating common files;<(

### CODE REVIEW

**Comment by sjg20** [comment]
Can we put these files into the main Zephyr tree? Why is a module needed?

**Comment by henrikbrixandersen** [comment]
Having those 12k LoC in a module allows downstream users to exclude them if not using this particular platform.

**Review by albertofloyd — APPROVED** [review]

**Comment by sjg20** [comment]
> Having those 12k LoC in a module allows downstream users to exclude them if not using this particular platform.

Yes I understand that, but why? As soon as we add tests for this code we will need it. 12k LoC is not a lot compared to the >2 million in Zephyr. The disadvantage is that the core code is somewhere else and must be updated with a separate PR, so is harder to keep in step

**Review by sjg20 — CHANGES_REQUESTED** [review]
I think this should be in the main repo

**Comment by keith-zephyr** [comment]
> > Having those 12k LoC in a module allows downstream users to exclude them if not using this particular platform.
> 
> Yes I understand that, but why? As soon as we add tests for this code we will need it. 12k LoC is not a lot compared to the >2 million in Zephyr. The disadvantage is that the core code is somewhere else and must be updated with a separate PR, so is harder to keep in step

I agree, it would be preferred to add these files to the main Zephyr repo.

**Comment by albertofloyd** [comment]
> ode is somewhere else and must be updated with a separate PR, so is harder to keep in step

This is MCHP-specific but it's there for all Zephyr HAL and modules https://docs.zephyrproject.org/latest/guides/modules.html

To keep track of specific HALs, and other module/components west is used. 
https://docs.zephyrproject.org/latest/guides/west/manifest.html

**Comment by sjg20** [comment]
> > ode is somewhere else and must be updated with a separate PR, so is harder to keep in step
> 
> This is not MCHP-specific but it's there for all Zephyr HAL and modules https://docs.zephyrproject.org/latest/guides/modules.html
> 
> To keep track of specific HALs, and other module/components west is used.
> https://docs.zephyrproject.org/latest/guides/west/manifest.html

Does MHCP mean Microchip? If so, it seems that the code in this PR is actually Microchip-specific. If it is not, can you please explain what other microcontrollers use it?

**Comment by albertofloyd** [comment]
> > > ode is somewhere else and must be updated with a separate PR, so is harder to keep in step
> > 
> > 
> > This is not MCHP-specific but it's there for all Zephyr HAL and modules https://docs.zephyrproject.org/latest/guides/modules.html
> > To keep track of specific HALs, and other module/components west is used.
> > https://docs.zephyrproject.org/latest/guides/west/manifest.html
> 
> Does MHCP mean Microchip? If so, it seems that the code in this PR is actually Microchip-specific. If it is not, can you please explain what other microcontrollers use it?

What I mean is that the module approach/usage is not Microchip-specific. It's the way all HAL and other Zephyr external modules are structured. Check the links given

**Comment by nashif** [comment]
@sjg20  is suggesting we move all those new headers into Zephyr and skip the module part completely. In the case of microchip and this new "HAL" it is actually just header files and no code that need to be shimmed, so all of the driver code (.c files) is in the tree and we depend on external headers to build this code. Maybe it is something to consider if the license allows that and if those files are all being used, ie, we should not import files into zephyr that are not used.

**Comment by sjg20** [comment]
> at I mean is that the module approach/usage is not Microchip-specific. It's the way all HAL and other Zephyr external modules are structured. Check the links given

I certainly understand that this is done. I even understand that several vendors do things this way (e.g. STM32), perhaps for historical reasons and for a desire to maintain their code somewhat separate from Zephyr. But I really don't see the point. It just makes things harder IMO, for the reasons I mention above.

**Comment by scottwcpg** [comment]
Abandoning.  Working on MEC172x downsized header for Zephyr SoC folder.

**Pull request closed without merging**
