### PR TITLE
modules: mec1501: Fix bugs in ACPI EC defines

### PR DESCRIPTION
**Pull request by scottwcpg**
ACPI EC Status register defines incorrect bit
position names corrected.

Signed-off-by: Scott Worley <scott.worley@microchip.com>

### CODE REVIEW

**Comment by galak** [comment]
Is there a corresponding PR in Zephyr for this?

**Comment by scottwcpg** [comment]
Zephyr issue #24241

**Comment by galak** [comment]
> Zephyr issue #24241

There needs to be PR on the Zephyr side that uses this PR to make sure this change doesn't break Zephyr.

**Comment by albertofloyd** [comment]
> > Zephyr issue #24241
> 
> There needs to be PR on the Zephyr side that uses this PR to make sure this change doesn't break Zephyr.

https://github.com/zephyrproject-rtos/zephyr/pull/24251

**Pull request merged**
