### PR TITLE
Mec1501 ecia update

### PR DESCRIPTION
**Pull request by scottwcpg**
Microchip MEC150x/152x HAL update broken into multiple commits.
Common header update adding BIT() macro if it is not defined elsewhere.
Interrupt source defines for all the ECIA GIRQ's.
ECIA register structure updated to provide named GIRQxy or GIRQ[] array access.
Missing ADC and analog comparator register defines added.
EC subystem defines updated.

### CODE REVIEW

**Comment by scottwcpg** [comment]
GitHub did not let me add reviewers.  Adding:
@albertofloyd
@nashif

**Comment by nashif** [comment]
> GitHub did not let me add reviewers. Adding:
> @albertofloyd
> @nashif

go here https://github.com/zephyrproject-rtos/hal_microchip/invitations and accept the invite

**Comment by scottwcpg** [comment]
The link is expired.  Could this be due to two forks?  My management wants to forks to be located at MCHP's GitHub area https://github.com/MicrochipTech/hal_microhip and zephyr. My user account is "scottwcpg" also has a forks for zephyr and hal_microchip.

**Comment by nashif** [comment]
I just resent it

**Review by albertofloyd — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Pull request merged**
